
{'date': 'Tue Sep 03 2019 09:34:31.27 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 12
  templo = Cena(DI["CENA"]
                                    ^
SyntaxError: invalid syntax
'''},
{'date': 'Tue Sep 03 2019 09:35:33.763 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 12
  cena = Cena(DI["CENA"]
                                  ^
SyntaxError: invalid syntax
'''},
{'date': 'Tue Sep 03 2019 09:36:31.704 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 13
  tesouro = Cena(DI["TESOURO"]
                                        ^
SyntaxError: invalid syntax
'''},
{'date': 'Tue Sep 03 2019 09:37:27.440 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 15
  fogo = Cena(DI
                          ^
SyntaxError: invalid syntax
'''},
{'date': 'Tue Sep 03 2019 09:38:44.987 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 25
    inca.inicia()
  module <module> line 15
    fogo = Cena(DI["fogo"])
KeyError: fogo
'''},
{'date': 'Tue Sep 03 2019 09:39:20.899 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 25
    inca.inicia()
  module <module> line 15
    fogo = Cena(DI["fogo"])
KeyError: fogo
'''},
{'date': 'Tue Sep 03 2019 09:40:01.789 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 25
    inca.inicia()
  module <module> line 15
    fogo = Cena(DI["fogo"])
KeyError: fogo
'''},
{'date': 'Tue Sep 03 2019 09:40:58.457 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 25
    inca.inicia()
  module <module> line 16
    templo.direita = tesouro
NameError: name 'templo' is not defined
'''},
{'date': 'Tue Sep 10 2019 09:28:30.407 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 20
  self.cena = Cena(imagem)
  ^
IndentationError: expected an indented block
'''},
{'date': 'Tue Sep 10 2019 09:28:58.258 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 20
  self.cena = Cena(imagem)
  ^
IndentationError: expected an indented block
'''},
{'date': 'Tue Sep 10 2019 10:28:17.876 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 4
  __author__ = "Carlo E. T. Oliveira carlo@ufrj.br"
  ^
IndentationError: unexpected indent
'''},
{'date': 'Tue Sep 10 2019 10:28:50.139 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module ruzwana.main line 40
  self.cena.direita = self.acampamento
  ^
IndentationError: expected an indented block
'''},
{'date': 'Tue Sep 10 2019 10:30:26.200 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module ruzwana.main line 40
  self.cena.direita = self.acampamento
  ^
IndentationError: expected an indented block
'''},
{'date': 'Tue Sep 10 2019 10:31:02.58 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 40
  def__init__(self):
                    ^
SyntaxError: invalid syntax
'''},
{'date': 'Tue Sep 10 2019 10:31:41.871 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 40
  def__init__(self):
                    ^
SyntaxError: invalid syntax
'''},
{'date': 'Tue Sep 10 2019 10:33:57.676 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 40
  def__init__(self):
                    ^
SyntaxError: invalid syntax
'''},
{'date': 'Tue Sep 10 2019 10:34:24.591 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 4
    from ruzwana.main import DI as RDI
ImportError: cannot import name 'DI'
'''},
{'date': 'Tue Sep 10 2019 10:39:14.924 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 60
    inca = Jogo()  # Inca()
  module <module> line 52
    self.baralho = Carta().baralho()
  module <module> line 42
    self.cartas = [Perigo(RDI[uma_imagem], uma_imagem) 
NameError: name 'RDI' is not defined
'''},
{'date': 'Tue Sep 10 2019 10:39:41.800 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 60
    inca = Jogo()  # Inca()
  module <module> line 52
    self.baralho = Carta().baralho()
  module <module> line 42
    self.cartas = [Perigo(DI[uma_imagem], uma_imagem) 
KeyError: PEDRAS
'''},
{'date': 'Tue Sep 10 2019 10:40:15.600 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 60
    inca = Jogo()  # Inca()
  module <module> line 52
    self.baralho = Carta().baralho()
  module <module> line 42
    self.cartas = [Perigo(DI[uma_imagem],uma_imagem) 
KeyError: MUMIA
'''},
{'date': 'Tue Sep 10 2019 10:41:56.100 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 4
  from _spy.vitollino.main import Cena
  ^
IndentationError: unexpected indent
'''},
{'date': 'Tue Sep 10 2019 10:42:36.776 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module ruzwana.main line 40
  self.cena.direita = self.acampamento
  ^
IndentationError: expected an indented block
'''},
{'date': 'Tue Sep 10 2019 10:46:34.848 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 18
  def __init__(self, imagem, tipo):
  ^
IndentationError: expected an indented block
'''},
{'date': 'Tue Sep 17 2019 09:31:47.342 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 4
    from ruzwana.main import DI as RDI
  module ruzwana.main line 66
    inca = Jogo()
  module ruzwana.main line 60
    self.baralho = Cartas().baralho()
  module ruzwana.main line 51
    carta.set_direita = (self.carta[ordem+1])
NameError: name 'carta' is not defined
'''},
{'date': 'Tue Sep 17 2019 09:34:49.990 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 4
    from ruzwana.main import DI as RDI
ImportError: cannot import name 'DI'
'''},