
{'date': 'Wed Sep 04 2019 11:17:45.666 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 6
  JOGADOR =
            ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Sep 04 2019 12:28:09.192 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 16
  def __init__(self) #dunder
                             ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Sep 04 2019 12:29:03.889 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 29
  for c_hoje, c_ama in baralho_zip #este for é outro comando tem que separar mesmo
                                                                                   ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Sep 04 2019 12:30:22.563 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 29
  for c_hoje, c_ama in baralho_zip 
                                    ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Sep 04 2019 12:32:16.568 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 31
  c_hoje.direita = c_ama
  ^
IndentationError: expected an indented block
'''},
{'date': 'Wed Sep 04 2019 12:32:44.672 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 57
    jogo.inicia()
  module <module> line 50
    tesouro.direita = mumia
NameError: name 'mumia' is not defined
'''},
{'date': 'Wed Sep 18 2019 17:01:40.68 GMt-0300 (Hora oficial do Brasil) -X- SuPyGirls -X-',
'error': '''
 module <string> line 11
  def vai(self):
  ^
IndentationError: unexpected indent
'''},
{'date': 'Wed Sep 18 2019 17:01:54.562 GMt-0300 (Hora oficial do Brasil) -X- SuPyGirls -X-',
'error': '''
 module <string> line 11
  def vai(self):
  ^
IndentationError: unexpected indent
'''},
{'date': 'Wed Sep 18 2019 17:06:08.130 GMt-0300 (Hora oficial do Brasil) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 28
    	Jogo()
  module <module> line 23
    		self.carta.proximo(self.templo)
AttributeError: 'Carta' object has no attribute 'proximo'
'''},
{'date': 'Wed Sep 18 2019 17:06:13.212 GMt-0300 (Hora oficial do Brasil) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 28
    	Jogo()
  module <module> line 23
    		self.carta.proximo(self.templo)
AttributeError: 'Carta' object has no attribute 'proximo'
'''},
{'date': 'Wed Sep 18 2019 17:06:18.972 GMt-0300 (Hora oficial do Brasil) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 28
    	Jogo()
  module <module> line 23
    		self.carta.proximo(self.templo)
AttributeError: 'Carta' object has no attribute 'proximo'
'''},
{'date': 'Wed Sep 18 2019 17:06:20.84 GMt-0300 (Hora oficial do Brasil) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 28
    	Jogo()
  module <module> line 23
    		self.carta.proximo(self.templo)
AttributeError: 'Carta' object has no attribute 'proximo'
'''},
{'date': 'Wed Sep 18 2019 17:06:21.110 GMt-0300 (Hora oficial do Brasil) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 28
    	Jogo()
  module <module> line 23
    		self.carta.proximo(self.templo)
AttributeError: 'Carta' object has no attribute 'proximo'
'''},
{'date': 'Wed Sep 18 2019 17:06:22.132 GMt-0300 (Hora oficial do Brasil) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 28
    	Jogo()
  module <module> line 23
    		self.carta.proximo(self.templo)
AttributeError: 'Carta' object has no attribute 'proximo'
'''},
{'date': 'Wed Sep 18 2019 17:06:23.162 GMt-0300 (Hora oficial do Brasil) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 28
    	Jogo()
  module <module> line 23
    		self.carta.proximo(self.templo)
AttributeError: 'Carta' object has no attribute 'proximo'
'''},
{'date': 'Wed Sep 18 2019 17:06:24.200 GMt-0300 (Hora oficial do Brasil) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 28
    	Jogo()
  module <module> line 23
    		self.carta.proximo(self.templo)
AttributeError: 'Carta' object has no attribute 'proximo'
'''},
{'date': 'Wed Sep 18 2019 17:07:08.222 GMt-0300 (Hora oficial do Brasil) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 28
    	Jogo()
  module <module> line 23
    		self.carta.proximo(self.templo)
AttributeError: 'Carta' object has no attribute 'proximo'
'''},
{'date': 'Wed Sep 18 2019 17:28:09.862 GMt-0300 (Hora oficial do Brasil) -X- SuPyGirls -X-',
'error': '''
RuntimeError: <InternalError: too much recursion>
'''},
{'date': 'Wed Sep 18 2019 17:37:06.320 GMt-0300 (Hora oficial do Brasil) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 52
    	Jogo()
  module <module> line 47
    self.carta.monta_baralho(self.carta)
AttributeError: 'Carta' object has no attribute 'monta_baralho'
'''},