
{'date': 'Mon Aug 26 2019 18:03:35.334 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 11
    monstro = Cena(MONSTRO)
NameError: name 'MONSTRO' is not defined
'''},
{'date': 'Mon Sep 02 2019 16:39:37.528 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 12
  templo = Cena(CENA)
  ^
IndentationError: expected an indented block
'''},
{'date': 'Mon Sep 02 2019 16:43:37.334 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 12
  templo = Cena(DI["CENA"])
  ^
IndentationError: expected an indented block
'''},
{'date': 'Mon Sep 02 2019 16:46:12.956 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 12
  templo = Cena (DI["CENA"])
  ^
IndentationError: expected an indented block
'''},
{'date': 'Mon Sep 02 2019 16:48:31.74 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 24
  if __name__ == "__main__":
                            ^
IndentationError: expected an indented block
'''},
{'date': 'Mon Sep 02 2019 16:51:03.832 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 27
    inca.inicia()
AttributeError: 'Inca' object has no attribute 'inicia'
'''},