
{'date': 'Tue Aug 27 2019 10:56:43.815 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module stacy.main line 5
  ARTEFATO = 
              ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Aug 28 2019 14:24:26.502 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 3
    from stacy.main import fogo
  module stacy.main line 40
    baralho.vai()
AttributeError: 'list' object has no attribute 'vai'
'''},
{'date': 'Tue Sep 03 2019 10:40:59.432 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 35
    inca = Jogo()  # Inca()
  module <module> line 30
    self.templo.direita = self.baralho[0]
IndexError: list index out of range
'''},
{'date': 'Tue Sep 10 2019 09:06:54.363 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 43
    inca = Jogo()  # Inca()
  module <module> line 37
    self.templo = Perigo(DI["TEMPLO"])
TypeError: __init__() missing 1 positional argument: imagem
'''},
{'date': 'Tue Sep 10 2019 10:31:28.38 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module ruzwana.main line 40
  self.cena.direita = self.acampamento
  ^
IndentationError: expected an indented block
'''},
{'date': 'Tue Sep 10 2019 10:40:53.232 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module ruzwana.main line 40
  self.cena.direita = self.acampamento
  ^
IndentationError: expected an indented block
'''},
{'date': 'Tue Sep 10 2019 10:41:04.107 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 4
    from ruzwana.main import DI as RDI
ImportError: cannot import name 'DI'
'''},
{'date': 'Tue Sep 10 2019 10:41:57.857 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module ruzwana.main line 40
  self.cena.direita = self.acampamento
  ^
IndentationError: expected an indented block
'''},
{'date': 'Tue Sep 10 2019 10:43:16.258 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 4
    from ruzwana.main import DI as RDI
ImportError: cannot import name 'DI'
'''},
{'date': 'Tue Sep 17 2019 09:20:41.907 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 4
    from ruzwana.main import DI as RDI
  module ruzwana.main line 66
    inca = Jogo()
  module ruzwana.main line 60
    self.baralho = Cartas().baralho()
  module ruzwana.main line 51
    carta.set_direita = (self.carta[ordem+1])
NameError: name 'carta' is not defined
'''},
{'date': 'Tue Sep 17 2019 09:37:04.801 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 4
    from ruzwana.main import DI as RDI
  module ruzwana.main line 66
    inca = Jogo()
  module ruzwana.main line 60
    self.baralho = Cartas().baralho()
  module ruzwana.main line 51
    carta.set_direita = (self.carta[ordem+1])
NameError: name 'carta' is not defined
'''},